### ISSUE TITLE
No romfiles found for game: SpaceInvaders-Atari2600

### ISSUE THREAD

**Issue by KejieLyu** [simoninithomas/Deep_reinforcement_learning_Course#64]
Hello, where can I download the game? I try to find the rom on internet but failed.

**Comment by Tigenzero** [comment]
duplicate of #31 
http://www.atarimania.com/rom_collection_archive_atari_2600_roms.html
unzip and put the roms folder under the space invaders folder
execute this command within the space invaders folder:
!python3 -m retro.import ./roms

**Comment by LucasColas** [comment]
It doesn't work for me. I'm trying to run on Google Colab.

**Comment by AlmeidaAlin3** [comment]
hey @LucasColas, on colab you can try this:
 
!wget http://www.atarimania.com/roms/Roms.rar
!python3 -m retro.import /content/ROMS
env = retro.make(game="SpaceInvaders-Atari2600")

**Comment by awybin** [comment]
On `!python3 -m retro.import /content/ROMS` I got the error:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/retro/import/__main__.py", line 4, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/retro/scripts/import_path.py", line 21, in main
    known_hashes = retro.data.get_known_hashes()
  File "/usr/local/lib/python3.10/dist-packages/retro/data/__init__.py", line 401, in get_known_hashes
    known_hashes[sha] = (game, ext, os.path.join(path(), curpath))
UnboundLocalError: local variable 'ext' referenced before assignment

any idea what could be the cause?
